### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by zhadier** [zhadier/Rent-A-Movie#21]
# Kanban Board Review :rice_cracker: 
- Below is the link to the Kanban board & there are 2 members in our team
- [Kanban Board](https://github.com/zhadier/JavaScript-Capstone/projects/2)

**Comment by o-rashad** [comment]
# Status: Changes Required ♻️

Asslam Alikom Team, @zhadier @gabyse1 👋😄,
I'm Omar and I will be your reviewer for this project 😊

There are some issues 🐞 that you still need to work on to go to the next project but you are almost there! 🏁🏁🏁

## Required Changes ♻️
Please complete these steps before continuing on your project

- [ ] Each of the team members should assign themselves to the correct cards. 
- [ ] Decide who will be the assignee for the cards marked as group tasks. 
- [ ] All cards on your Kanban board should have assignees.

Video explanation on how to assign yourself or your teammates 👇 
https://www.loom.com/share/a71d3b01027749e48b5b4b1621c75327


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zhadier** [comment]
Thank you so much for such a professional review. This is by far one of the best reviews I've gotten and the effort you've put in is greatly appreciated. I will try to be the same when or if I become a code reviewer :)

**Comment by julie-ify** [comment]
## Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
